### ISSUE TITLE
请教个问题,求解答.码主.

### ISSUE THREAD

**Issue by Vander-liu** [chiemy/CardView#3]
我使用您制作的控件之后,感觉界面还是其他的都非常的棒.
但是根据我的需求,我想在当前卡片操作之后,到下一轮回滚到这个卡片的时候,这些状态能够保存...但是不知道怎么实现这样的功能 .如果 您方便,可否私信我一个邮箱.

**Comment by chiemy** [comment]
如果你指的状态是 CheckBox 或 RadioButton 等的状态的话，就像普通的 ListView 一样，它不会帮你保存，需要你自己保存

**Comment by WanDa1993** [comment]
很开心楼主能够回答我的问题,时隔半年,当时的具体的问题我也忘掉了.我记得当时我竟然都去搜你的知乎然后去私信你,.,,,,,对你造成的打扰感到抱歉.
